version: '3'

volumes:
  datenbank:
  code:

services: 
  webserver:
    build: webserver
    ports: 
     - 80:80
    volumes:
      - .htdocs:/var/www/html 
  database:
    image: mysql:latest
    container_name: mysql
    ports: 
     - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD="Pappelweg!11"
     - MYSQL_DATABASE="WebProgrammierung"
     - MYSQL_USER="root"
     - MYSQL_PASSWORD="Pappelweg!11"
    volumes:
     - datenbank:/var/lib/mysql 
    

